Анализ образа системы в режиме командной строки в контейнере с файлом источником помеченных данных
ispras/natch pull request #12
Opened 2023-03-25 20:54 UTC by Orlovskiiparen

2023-03-26 15:19 UTC, DmitryJustDmitry commented on 1_quickstart.md
> +Установить неграфическую цель "по умолчанию": `systemctl set-default multi-user.target`
@Orlovskiiparen необходимо сделать примечание "Важно" (посмотри, как они выше оформляются), где написать, что приведённый ниже способ (тюнинг GRUB и т.д.) в вашем Линуксе может отличаться о работающего в тестовом образе!

2023-03-26 15:19 UTC, DmitryJustDmitry commented on 1_quickstart.md
> +-nographic \
@Orlovskiiparen я тебе ранее комментил, что вот эти параметры нужно явно пояснить "для чайнников". Также, сделай примечание, что данные параметры самим Natch вставляются во все скрипты автоматически, что вы увидите далее в разделе N (сделать кликательную ссылку на соответствующий подпункт)

2023-03-26 15:19 UTC, DmitryJustDmitry commented on 1_quickstart.md
> +
Кратко описать сценарий работы с этой программой - это простой консольный парсер, который пытается распарситб xml-файл, подаваемый на вход в качестве первого параметра...

2023-04-11 12:42 UTC, notawa commented
ну на свои замечания я тут реакции никакой не увидела ¯\_(ツ)_/¯

2023-05-10 07:48 UTC, notawa requested changes

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Выполнить настройку Natch согласно пункту 1.3.1.3.
про номера пунктов я уже писала. тут автоматической нумерации нет и если что-то изменится, то все поедет. пиши лучше название пункта и ссылку на него

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
>  Выполнить запись трассы согласно пункта 1.3.1.4, на этапе с созданием снапшота, необходимо на хостовой машине открыть новое окно терминала и выполнить подключение к тестовой ОС:
опять номер пункта

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +В данном разделе описан пример использования natch в режиме командной строки, что в ряде сценариев, например, для использоывания на сервере значительно удобнее. Помимо этого, в разделе описан вариант
использоывания

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Установить неграфическую цель "по умолчанию": `systemctl set-default multi-user.target`
в тестовом образе уже все настроено для этой работы. можно сделать инструкцию как подготовить свой образ. типа на примере дебиана это делается так-то, ну в а тестовом ничего делать не надо

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Удалить строку:
а почему с новой строки и с большой буквы, если это явно продолжение

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Далее необходимо перенести объект оценки в виртуальную машину, аналогично пункту 1.2.3, переместить 3 сэмпла (sydr_0_int_overflow_1_unsigned, sydr_1_int_overflow_0_unsigned, sydr_2_int_overflow_0_uns
пункт

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Удалить строку:
и пункт опять

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +В конфигурационных файлах 'run_record, run_replay, run_qemu' необходимо изменить конфигурации и добавить '-monitor tcp:0.0.0.0:7799,server,nowait' крайней строкой в конфигурационном файле.
ну вообще мы называем это скриптами запуска и лучше с расширением

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Запустить snatch, согласно пункта 1.3.1.7
ссылки ссылки ссылки

2023-05-10 07:48 UTC, notawa commented on 1_quickstart.md
> +Запустить snatch, согласно пункта 1.3.1.7
уаправления

2023-05-10 15:01 UTC, notawa commented on 1_quickstart.md
> +#### <a name="config_natch_test_image"></a> 1.3.1.3. Настройка Natch для работы с тестовым образом ОС
убери пж пробелы после > а то в пдф некрасиво будет

2023-05-10 15:01 UTC, notawa commented on 1_quickstart.md
> +#### <a name="record_scenario"></a> 1.3.1.4. Запись сценария работы
и тут

2023-05-10 15:01 UTC, notawa commented on 1_quickstart.md
> +Выполнить запись трассы согласно [пункта](#record_scenario), на этапе с созданием снапшота, необходимо на хостовой машине открыть новое окно терминала и выполнить подключение к тестовой ОС:
может пунктУ? вообще я конечно предполагала название пункта написать для наглядности. да вообще и не только, потому чо иногда ссылки кривовато открываются и можно ввестись в заблужение. но если лень, это я могу сама потом поправить

2023-05-11 07:43 UTC, merged